// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVGZ-rczTuS_x53EOO4kJuwvcTubHDDY',
    appId: '1:155262253357:web:5b16d927e68658d6d8fba4',
    messagingSenderId: '155262253357',
    projectId: 'welvors-989fe',
    authDomain: 'welvors-989fe.firebaseapp.com',
    storageBucket: 'welvors-989fe.firebasestorage.app',
    measurementId: 'G-YEEG8W8M42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACJTCp5042IQnAwPeCdzSO4XZaEl8AQjE',
    appId: '1:155262253357:android:83b449bdffe53abad8fba4',
    messagingSenderId: '155262253357',
    projectId: 'welvors-989fe',
    storageBucket: 'welvors-989fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Omt-wnKOJcv4kTPfNIvN3VGlg-QseCY',
    appId: '1:155262253357:ios:a73bb8907a1891fcd8fba4',
    messagingSenderId: '155262253357',
    projectId: 'welvors-989fe',
    storageBucket: 'welvors-989fe.firebasestorage.app',
    iosBundleId: 'com.infynod.welvors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Omt-wnKOJcv4kTPfNIvN3VGlg-QseCY',
    appId: '1:155262253357:ios:a73bb8907a1891fcd8fba4',
    messagingSenderId: '155262253357',
    projectId: 'welvors-989fe',
    storageBucket: 'welvors-989fe.firebasestorage.app',
    iosBundleId: 'com.infynod.welvors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiVGZ-rczTuS_x53EOO4kJuwvcTubHDDY',
    appId: '1:155262253357:web:993e591bcbe50795d8fba4',
    messagingSenderId: '155262253357',
    projectId: 'welvors-989fe',
    authDomain: 'welvors-989fe.firebaseapp.com',
    storageBucket: 'welvors-989fe.firebasestorage.app',
    measurementId: 'G-SPT4KY6ZC2',
  );
}
